### ISSUE TITLE
How to reset the Progress Bar

### ISSUE THREAD

**Issue by ArslanKathia** [carlosmuvi/SegmentedProgressBar#1]
First time its fill smoothly when i reused this progressbar its already filled. I am also reset the container background color again when its filled. 
Kindly help me?

**Comment by carlosmuvi** [comment]
Hi @ArslanKathia, thanks for using this component!

Not sure if this is your problem, but I added a `reset` method, and also reset the existing filling states when calling `setCompletedSegments`.

Let me know if it works for you!

**Comment by ArslanKathia** [comment]
You replied me very late !!!
