### ISSUE TITLE
how can i remove bar corner radius.. i checked Source code of lib..haven't found any method to remove that.

### ISSUE THREAD

**Issue by 123pankaj** [carlosmuvi/SegmentedProgressBar#14]

**Comment by carlosmuvi** [comment]
I'm not planning on adding square borders, but feel free to fork the library and add the feature.

Take a look at the 'drawRoundedRect' method. Replacing that by regular drawRect should do the trick.

**Comment by DmitryM9** [comment]
Hi. Could it be better to make the corner radius customizable?

**Comment by carlosmuvi** [comment]
Available in https://github.com/carlosmuvi/SegmentedProgressBar/releases/tag/0.8.2.

Thanls @DmitryM9 !
