### ISSUE TITLE
manifest merger failed

### ISSUE THREAD

**Issue by dhrutimistry8** [carlosmuvi/SegmentedProgressBar#23]
add in "latest" android studio version and gives manifest merger failed error.

**Comment by dinesh750** [comment]
Migrate to Android x

**Comment by VittoriDavide** [comment]
or maybe you can try with the previous version 'com.github.carlosmuvi:SegmentedProgressBar:0.7.0'

**Comment by carlosmuvi** [comment]
Yep! You'll need to either migrate to AndroidX or use the last version before the lib migration, which happens to be `0.7.0`.
