### ISSUE TITLE
Segment progressbar use with viewpager transform

### ISSUE THREAD

**Issue by meghaandroidwmt** [carlosmuvi/SegmentedProgressBar#3]
when  first fragment open and it total segment count progress finish. it automatically change next page like instagram story.It works proper but when first screen is open ,in background next fragment progress also start with it . actually its wrong because of it process flow is not proper manage . please can you help me for how can i manage it properly.its progress start with visible fragment only and not in next fragment until it not visible.

**Comment by carlosmuvi** [comment]
I'm not sure I understand the issue you're having. Can you elaborate or provide your implementation?

**Comment by tarunkonda** [comment]
@meghaandroidwmt is it viewpager fragments ?? if it is viewpager  fragments frag1 and frag2 also execute same time .. i think  the issue bcoz of that..

**Comment by meghaandroidwmt** [comment]
yes i also think same and i also search for that also but i dont want it so there is any solution?

**Comment by carlosmuvi** [comment]
If you're working with view pager fragments, you just need it to have the progress bar in the activity that holds the viewpager, and manage it in the 'onPageSelected' callback. 

https://developer.android.com/reference/android/support/v4/view/ViewPager.OnPageChangeListener.html

**Comment by Parth20** [comment]
@meghaandroidwmt  Can you please tell me how to set auto start while complete one part of segment for get next segment .e.g. I have added 6 part of segment count and I want to set autostart for completion of no. 1 segment  and open no. 2 segment .

**Comment by tarunkonda** [comment]
still i  didn't get your error ....
but it may helps to u
private static boolean m_iAmVisible;

@Override
public void setUserVisibleHint(boolean isVisibleToUser) { 
    super.setUserVisibleHint(isVisibleToUser);
    m_iAmVisible = isVisibleToUser;

    if (m_iAmVisible) { 
        Log.d(localTAG, "this fragment is now visible");
    } else {  
        Log.d(localTAG, "this fragment is now invisible");
    }
}

**Comment by Parth20** [comment]
If once I start segment progress then it will continue till end without stopping or without click button for start progress of next segment. 
If first segment's progress is finish then automatically start next progress. 
I used Handler but it's not work properly. I want to do same as whats app status  new feature   for showing multiple status of one user.

**Comment by carlosmuvi** [comment]
The best way now is to use a listener (Added support in 0.8.3). Just call playNextSegment when the callback is triggered.
