### ISSUE TITLE
How do I start the first play and start second automatically?

### ISSUE THREAD

**Issue by kangjie6501** [carlosmuvi/SegmentedProgressBar#6]
How do I start the first play and start second automatically? I need each play to complete the listener.

**Comment by carlosmuvi** [comment]
The best way to achieve this is to create a Listener that will be called when a segment is completed. I will add it to the library soon, stay tuned!

**Comment by RayVaniya** [comment]
i have total 5 count(segments) and i have this code..

 if (segmentedProgressBar.getCompletedSegments() != 4) {
            segmentedProgressBar.playSegment(1000);
        }

but not working, it fill only 1 segment, how to fill more than 1 segments with animation @carlosmuvi

**Comment by jjimenez0611** [comment]
@carlosmuvi do you create the listener?

**Comment by uzman** [comment]
Hi,
is there any progress for "starting next automatically" ?

**Comment by carlosmuvi** [comment]
The best way now is to use a listener (Added support in `0.8.3`). Just call `playNextSegment` when the callback is triggered.
